# # Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# platform :ios, min_ios_version_supported
# prepare_react_native_project!



 def node_require(script)
   # Resolve script with node to allow for hoisting
   require Pod::Executable.execute_command('node', ['-p',
     "require.resolve(
       '#{script}',
       {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Use it to require both react-native's and this package's scripts:
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!



# ⬇️ uncomment the permissions you need
setup_permissions([
  # 'AppTrackingTransparency',
  # 'Bluetooth',
  # 'Calendars',
  # 'CalendarsWriteOnly',
  'Camera',
  # 'Contacts',
  # 'FaceID',
  # 'LocationAccuracy',
  # 'LocationAlways',
  # 'LocationWhenInUse',
  # 'MediaLibrary',
  # 'Microphone',
  # 'Motion',
  # 'Notifications',
  # 'PhotoLibrary',
  # 'PhotoLibraryAddOnly',
  # 'Reminders',
  # 'Siri',
  # 'SpeechRecognition',
  # 'StoreKit',
])



linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AIME' do
  config = use_native_modules!

  # use_frameworks! :linkage => :dynamic
  # $RNFirebaseAsStaticFramework = true


  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,  # explicitly enable Hermes if you're using it
    # :fabric_enabled => true,  # if using new architecture
    :app_path => "#{Pod::Config.instance.installation_root}/.."
    # An absolute path to your application root.
    # :app_path => "#{Pod::Config.instance.installation_root}/.."

# # Add other permissions you need here

    
  )
  pod 'GoogleUtilities', :modular_headers => true
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseMessaging', :modular_headers => true
  pod 'biosensesignal-react-native-sdk',  :path => '../node_modules/biosensesignal-react-native-sdk'
  target 'AIMETests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    # ---- Add header exposure patches here ----
    installer.pods_project.targets.each do |target|
      # For pods that need ReactCommon headers, add include paths
      if target.name.include?('ReactCommon') || target.name.include?('RCT') || target.name.include?('JSI')
        target.build_configurations.each do |config|
          config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
          config.build_settings['HEADER_SEARCH_PATHS'] << "$(SRCROOT)/../node_modules/react-native/ReactCommon"
          config.build_settings['HEADER_SEARCH_PATHS'] << "$(SRCROOT)/../node_modules/react-native/ReactCommon/jsi"
        end
      end
    end
  end
end
